---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gatekeeper.yaml

patchesJson6902:
- target:
    name: .*
    kind: Gatekeeper
    version: v1alpha1
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "-2"
